# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东任务2

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_task
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          git clone https://github.com/lxk0301/jd_scripts.git ~/jd_scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/jd_scripts
          git checkout master
          npm install

      - name: '运行 【种豆得豆】'
        run: |
          cd ~/jd_scripts
          node jd_plantBean.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}

      - name: '运行 【京东超市】'
        run: |
          cd ~/jd_scripts
          node jd_superMarket.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          
      - name: '运行 【东东水果】'
        run: |
          cd ~/jd_scripts
          node jd_fruit.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
