# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青抽青豆

on:
  workflow_dispatch:
  schedule:
    - cron: '10 16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: zq
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.YOUTH_HEADER
        run: |
          git clone https://github.com/1217079729/TaskAction.git ~/TaskAction
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.YOUTH_HEADER
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.YOUTH_HEADER
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.YOUTH_HEADER
        run: |
          cd ~/TaskAction
          git checkout master
          npm install
      - name: '运行 【中青抽青豆】'
        if: env.YOUTH_HEADER
        run: |
          cd ~/TaskAction/workflow
          node youth_sign.js
        env:
          TZ: Asia/shanghai
          YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
          YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
          YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
