# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: äº¬ä¸œä¸´æ—¶ä»»åŠ¡

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_job
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          git clone https://github.com/1217079729/TaskAction.git ~/TaskAction
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # ä½¿ç”¨ GitHub å®˜æ–¹çš„ç¼“å­˜ Actionã€‚
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ä½¿ç”¨ package-lock.json çš„ Hash ä½œä¸ºç¼“å­˜çš„ keyã€‚ä¹Ÿå¯ä»¥ä½¿ç”¨ package.json ä»£æ›¿
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/TaskAction
          git checkout jd_code
          npm install

      - name: 'è¿è¡Œ ã€äº¬ä¸œç‚¸å¹´å…½ã€‘'
        run: |
          cd ~/TaskAction
          node jd_nian.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

          
      - name: 'è¿è¡Œ ã€é›†é­ç‚®èµ¢äº¬è±†ğŸ§¨ã€‘'
        run: |
          cd ~/TaskAction
          node jd_firecrackers.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œç‚¸å¹´å…½ç­¾åˆ°ä»»åŠ¡ğŸ§¨ã€‘'
        run: |
          cd ~/TaskAction
          node jd_nian_sign.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œç‚¸å¹´å…½ARğŸ§¨ã€‘'
        run: |
          cd ~/TaskAction
          node jd_nian_ar.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}

      - name: 'è¿è¡Œ ã€äº¬ä¸œç‚¸å¹´å…½å°ç¨‹åºğŸ§¨ã€‘'
        run: |
          cd ~/TaskAction
          node jd_nian_wechat.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}

      - name: 'è¿è¡Œ ã€äº¬ä¸œç¥ä»™ä¹¦é™¢ã€‘'
        run: |
          cd ~/TaskAction
          node jd_immortal.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

      - name: 'è¿è¡Œ ã€äº¬ä¸œæ‰‹æœºå¹´ç»ˆå¥–ã€‘'
        run: |
          cd ~/TaskAction
          node jd_festival.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œå¹´è´§èŠ‚ã€‘'
        run: |
          cd ~/TaskAction
          node jd_nh.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

