# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: äº¬ä¸œå¾ªç¯ä»»åŠ¡

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_job
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          git clone https://github.com/1217079729/TaskAction.git ~/TaskAction
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # ä½¿ç”¨ GitHub å®˜æ–¹çš„ç¼“å­˜ Actionã€‚
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ä½¿ç”¨ package-lock.json çš„ Hash ä½œä¸ºç¼“å­˜çš„ keyã€‚ä¹Ÿå¯ä»¥ä½¿ç”¨ package.json ä»£æ›¿
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/TaskAction
          git checkout jd_code
          npm install

      - name: 'è¿è¡Œ ã€ä¸œä¸œå†œåœºã€‘'
        run: |
          cd ~/TaskAction
          node jd_fruit.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€ä¸œä¸œèŒå® ã€‘'
        run: |
          cd ~/TaskAction
          node jd_pet.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€å£è¢‹ä¹¦åº—ã€‘'
        run: |
          cd ~/TaskAction
          node jd_bookshop.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€äº¬å–œå†œåœºã€‘'
        run: |
          cd ~/TaskAction
          node jd_jxnc.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€å® æ±ªæ±ªç§¯åˆ†å…‘æ¢å¥–å“ã€‘'
        run: |
          cd ~/TaskAction
          node jd_joy_reward.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€å® æ±ªæ±ªå·å¥½å‹ç§¯åˆ†ä¸ç‹—ã€‘'
        run: |
          cd ~/TaskAction
          node jd_joy_steal.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

      - name: 'è¿è¡Œ ã€ç‚¹ç‚¹åˆ¸ã€‘'
        run: |
          cd ~/TaskAction
          node jd_necklace.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œç›´æ’­18è±†ã€‘'
        run: |
          cd ~/TaskAction
          node jd_live.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€å–å…³äº¬ä¸œåº—é“ºå•†å“ã€‘'
        run: |
          cd ~/TaskAction
          node jd_unsubscribe.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€äº¬ä¸œå¤©å¤©åŠ é€Ÿã€‘'
        run: |
          cd ~/TaskAction
          node jd_speed.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€å¤©å¤©æé¹…ã€‘'
        run: |
          cd ~/TaskAction
          node jd_daily_egg.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€ä¸œä¸œè¶…å¸‚ã€‘'
        run: |
          cd ~/TaskAction
          node jd_superMarket.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      # æ ¹æ®ä¸Šæ¸¸å¾—çŸ¥è¯¥è„šæœ¬æœ‰é»‘å·é£é™©
      #      - name: 'è¿è¡Œ ã€äº¬ä¸œå®¶åº­å·ã€‘'
      #        run: |
      #          cd ~/TaskAction
      #          node jd_family.js
      #        env:
      #          JD_COOKIE: ${{ secrets.JD_COOKIE }}

      - name: 'è¿è¡Œ ã€äº¬ä¸œç‚¸å¹´å…½ã€‘'
        run: |
          cd ~/TaskAction
          node jd_nian.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€ä¸œä¸œçˆ±æ¶ˆé™¤ã€‘'
        run: |
          cd ~/TaskAction
          node jd_xxl.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

          
      - name: 'è¿è¡Œ ã€é›†é­ç‚®èµ¢äº¬è±†ğŸ§¨ã€‘'
        run: |
          cd ~/TaskAction
          node jd_firecrackers.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

