# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: å·¥ä¸šå“çˆ±æ¶ˆé™¤

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_job
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          git clone https://github.com/1217079729/TaskAction.git ~/TaskAction
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # ä½¿ç”¨ GitHub å®˜æ–¹çš„ç¼“å­˜ Actionã€‚
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ä½¿ç”¨ package-lock.json çš„ Hash ä½œä¸ºç¼“å­˜çš„ keyã€‚ä¹Ÿå¯ä»¥ä½¿ç”¨ package.json ä»£æ›¿
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/TaskAction
          git checkout jd_code
          npm install
          

      - name: 'è¿è¡Œ ã€äº¬ä¸œç‚¸å¹´å…½é¢†çˆ†ç«¹ğŸ§¨ã€‘'
        run: |
          cd ~/TaskAction
          node jd_nianCollect.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: 'è¿è¡Œ ã€å·¥ä¸šå“çˆ±æ¶ˆé™¤ã€‘'
        run: |
          cd ~/TaskAction
          node jd_gyec.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

