# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 快手签到

on:
  workflow_dispatch:
  schedule:
    - cron: '5 16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: 快手签到
jobs:
  build:
    env:
      KS_TOKEN: ${{ secrets.KS_TOKEN }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.KS_TOKEN
        run: |
          git clone https://github.com/Sunert/Scripts.git ~/Scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.KS_TOKEN
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.KS_TOKEN
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.KS_TOKEN
        run: |
          cd ~/Scripts
          git checkout master
          npm install
      - name: '运行 【快手签到】'
        if: env.KS_TOKEN
        run: |
          cd ~/Scripts/Task
          node kuaishou.js
        env:
          TZ: Asia/shanghai
          KS_TOKEN: ${{ secrets.KS_TOKEN }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
